title: "Mavis' Miniatures"
author: "chisaipete"
description: "A compendium of DnD miniatures that organizes them in various classifications."
url: "https://MavisMiniatures.github.io"
source-url: "https://github.com/MavisMiniatures/MavisMiniatures.github.io"
baseurl: ""  # Set to empty string
exclude: ['Rakefile', 'README.md']
livereload: true
incremental: true
collections:
  creatures:
    output: true
    permalink: "/creature/:name"
  tags:
    output: true
    permalink: "/tag/:name"
  miniatures:
    output: true
    permalink: /miniature/:name/


