title: "MavisMiniatures"
author: "MavisMiniatures"
description: "A searchable D&D 5e miniature list."
url: "https://mavisminiatures.github.io"
source-url: "https://github.com/MavisMiniatures/MavisMiniatures"
baseurl: "/MavisMiniatures"
exclude: ['Rakefile', 'README.md']
collections:
  creatures:
    output: true
    permalink: "/creature/:name"
  tags:
    output: true
    permalink: "/tag/:name"
