name: pages-build-deployment

on:
  workflow_dispatch: # This allows you to manually trigger the workflow from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a script
      run: echo "This is a manual workflow run"
